name: Release

on:
    push

jobs:
    release:
        runs-on: windows-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
            - run: npm i --force
            - run: npm run make
            - name: Set the value
              id: step_one
              run: |
                  echo "APP_VERSION=$(cat package.json | sed -n -e '/"version":/ s/^."(.)".*/\1/p')" >> $GITHUB_ENV
            - uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: "./out/make/squirrel.windows/x64/Neru OSC Controller-${{ env.APP_VERSION }} Setup.exe"
                  asset_name: "NeruOscController_v${{ env.APP_VERSION }}.exe"
                  release_name: "Release v${{ env.APP_VERSION }}"
                  tag: "v${{ env.APP_VERSION }}"
                  overwrite: true